### ISSUE TITLE
Threshold values should be +/-0.05 ... not +/-0.5

### ISSUE THREAD

**Issue by cjhutto** [vaderSentiment/vaderSentiment-js#5]
Typo in the threshold values stated in the README.  The entire compound score goes from -1 to 1, with 0 being neutral... so one would expect the thresholds for neutral to be very close to zero, allowing for only a little variance. Also, the published paper that the code is based on states that the thresholds for neutral are +-0.05.

**Comment by nimaeskandary** [comment]
Thanks cj, fixed in https://github.com/vaderSentiment/vaderSentiment-js/pull/6
